baseURL = "https://rafikahmh.github.io/"
languageCode = "en-us"
title = "Rafikah Halim"
theme = "kube"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Rafikah Halim" # add your company name
  github = "rafikahMH" # add your github profile name
  twitter = "" # add your twitter profile
  email = "rafikahMH"

[[menu.main]]
    name = "Work"
    weight = 1
    url = "/work/"
[[menu.main]]
    name = "Notes"
    weight = 2
    url = "/notes/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"
